### ISSUE TITLE
_resize函数this对象的问题

### ISSUE THREAD

**Issue by hjyker** [react-component/steps#11]
你好，我很想请教一个问题，我单独安装Steps使用，拖动改变窗口大小时候，会报这样的错误：
`Uncaught Invariant Violation: Element appears to be neither ReactComponent nor DOMNode`
显示错误是在_resize函数里面的 `const w = Math.floor(ReactDOM.findDOMNode(this).offsetWidth);`
this显示为window对象而不是我们这个Steps对象， 所以findDOMNode不支持非ReactElement就报错了；但是在antd组件里面却没有错误，查看antd的steps组件和最终的export文件也看不出什么端倪，感觉没有做什么循序bind的事情。

**Comment by afc163** [comment]
1.5.3
