### ISSUE TITLE
steps 渲染会有闪烁。最后一个 step 会掉到下一行

### ISSUE THREAD

**Issue by clarkhan** [react-component/steps#14]
在组件上的 componentDidMount 打断点会清楚看到这个现象。

![image](https://cloud.githubusercontent.com/assets/3722265/15281683/0b2580e0-1b70-11e6-8e56-2dd5c5562ce8.png)

这是折行的样子：
![image](https://cloud.githubusercontent.com/assets/3722265/15281599/503cc46e-1b6f-11e6-82dc-e3d4533bc0b0.png)

测试 Demo ： http://codepen.io/clarkhan/pen/NNmZgx 其实和示例是一样的。

（ps：刚刚没编辑好一不小心回车了，囧……）

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by clarkhan** [comment]
已更新了示例

**Comment by haibinyu** [comment]
这个应该是因为steps组件在mount之后要动态更新最后一个step的位置，加了断点之后，在更新前就暂停运行了吧。

**Comment by clarkhan** [comment]
断点是让这个过程明显了。不用断点，仔细看也能看到这样一个过程：先折行，后恢复。所以会导致页面闪烁。

**Comment by benjycui** [comment]
@afc163 这个感觉不是很好改，可能又要重构才能解决。

**Comment by afc163** [comment]
其实考虑过这个问题，当时手误写了个 `vertical-align: hidden;` 。
