### ISSUE TITLE
Warning that timeout callback sets state on unmounted component

### ISSUE THREAD

**Issue by ThisSentenceIsFalse** [react-component/steps#16]
<pre>
warning.js?8a56:44 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
warning
  @ warning.js?8a56:44getInternalInstanceReadyForUpdate
  @ ReactUpdateQueue.js?fd2c:45ReactUpdateQueue.enqueueSetState
  @ ReactUpdateQueue.js?fd2c:192ReactComponent.setState
  @ ReactComponent.js?702a:67(anonymous function)
  @ Steps.js?da93:51
</pre>

React: 15.0.2; react-router: 2.4.0; webpack: 1.12.14.

I can't give too many specific details as this is not a personal project.

I can reproduce this by routing away from the page which embeds the step component, or by forcing a hot reload with webpack. My belief, as I've seen this sort of warning a few times, is that: 

* a componentDidUpdate call occurs right before unmount (don't know if this is a canonical React lifecycle order or simple occurence or an effect of the packages)
* the call to setState is async and occurs after the unmount, generating the no-op warning.

As far as I've read the code, you could solve it by guarding the call with a 'mounted' flag (which is set in the other lifecycle methods: willmount/willunmount) or simply setting state synchronously in componentDidUpdate (in fact, as far as I've seen, the state change will only be changed after the lifecycle method anyway). Cheers for the component.

**Comment by jpmn** [comment]
I am still experiencing this warning when running tests on components using this. Any idea how I can deal with it?
