### ISSUE TITLE
Warning: `NaN` is an invalid value for the `marginRight` css style property. Check the render method of `Step`

### ISSUE THREAD

**Issue by sonhgc00016** [react-component/steps#19]
When I'm using Steps with only 1 Step this warning appear please check this condition

**Comment by benjycui** [comment]
Why do you need Steps with one Step...

**Comment by sonhgc00016** [comment]
I have a list update real-time status, next status depends on the previous status and doesn't want the user to see all of my list status. First time render my list status have only one status and this warning appear

**Comment by benjycui** [comment]
Actually, there is no warning.. 

![image](https://cloud.githubusercontent.com/assets/3580607/19543734/30ee4f7a-96ac-11e6-8a6e-d807790d667e.png)

Please provide a re-producible demo.

**Comment by OhCoder** [comment]
Actually, I meet the warning too with one Step...
So, I found the this issue...

**Comment by sonhgc00016** [comment]
You can reproduce this warning with only 1 step like this:
```
<Steps current={0}>
    <Step className='initial' title='initial' icon={<Icon name='archive'/>}/>
</Steps>
```

**Comment by benjycui** [comment]
How about an online demo?  @sonhgc00016

**Comment by sonhgc00016** [comment]
I think you can fix this by check const adjustMarginRight before assign it for marginRight in https://github.com/react-component/steps/blob/master/src/Step.jsx

**Comment by benjycui** [comment]
A demo to re-producible this issue it better a solution, for we can test it.

**Comment by just-boris** [comment]
I am having this problem as well when I run tests with Jest in JSDOM. The problem in the following line

```
const lastStepOffsetWidth = domNode.lastChild.offsetWidth + 1;
```

JSDOM is a kind of headless browser, and elements there don't have `offsetWidth`, it is `undefined`, so the result of this expression will be `NaN`, that produces the warning.

Maybe @sonhgc00016 got the problem under similar conditions.
