### ISSUE TITLE
marginRight 不停改变

### ISSUE THREAD

**Issue by warmhug** [react-component/steps#22]
![gg](https://cloud.githubusercontent.com/assets/2011119/20790395/20890612-b7f3-11e6-8cf2-78223db58831.gif)

**Comment by afc163** [comment]
给个 codepen 重现。

**Comment by afc163** [comment]
我看 antd-mobile 里没有水平的 Steps，在哪遇到的。

**Comment by silentcloud** [comment]
@afc163 新需求，这次新加的，外部用户需求 https://github.com/ant-design/ant-design-mobile/issues/498

**Comment by afc163** [comment]
```diff
-              ? null : -(this.state.lastStepOffsetWidth / lastIndex + 1);
+              ? null : -Math.floor(this.state.lastStepOffsetWidth / lastIndex);
```

@warmhug 试试本地 node_modules 里面 https://github.com/react-component/steps/blob/dd6aa9445b5eef64d27dfe0ec0cbc84e6f08a509/src/Steps.jsx#L58 这行改成上面这样行不行。

**Comment by warmhug** [comment]
不刷新了，不过计算位置不太对

**Comment by afc163** [comment]
还是有问题，不知道为啥 marginRight 会影响最后一个元素的宽度计算。

**Comment by afc163** [comment]
我本地重现了。

**Comment by afc163** [comment]
```diff
-              ? null : -(this.state.lastStepOffsetWidth / lastIndex + 1);
+             ? null : -Math.round(this.state.lastStepOffsetWidth / lastIndex + 1);
```

这样改，我本地好了。

**Comment by afc163** [comment]
你试试，没问题我发一个 patch。

**Comment by warmhug** [comment]
不换行了，图标位置不太对，是样式写法问题？
![image](https://cloud.githubusercontent.com/assets/2011119/20796374/d13331be-b810-11e6-8994-be532daf5259.png)

**Comment by afc163** [comment]
图标位置好像和这个 bug 没关系，感觉是样式问题。

**Comment by afc163** [comment]
已发 2.2.1，重新安装。
