### ISSUE TITLE
icon 名不要写死

### ISSUE THREAD

**Issue by warmhug** [react-component/steps#23]
https://github.com/react-component/steps/blob/master/src/Step.jsx#L18-L19
![image](https://cloud.githubusercontent.com/assets/2011119/20841379/8f12b50a-b8ee-11e6-93e5-fcbdae872cd0.png)

**Comment by afc163** [comment]
https://ant.design/components/steps/#components-steps-demo-icon

**Comment by warmhug** [comment]
这个知道，主要是处理 Steps (不是 Step) 上设置 status="error" 的情况、会走到这个逻辑。除非再在上层写代码覆盖这个逻辑、那样稍麻烦。简单做法还是这里的 icon 名字支持自定义、现在的可以作为默认值。

**Comment by afc163** [comment]
可以自定义的 `<Step icon="xxx" />`，会覆盖原有的 icon。

**Comment by afc163** [comment]
错误处理参考：https://ant.design/components/steps/#components-steps-demo-error

**Comment by afc163** [comment]
看上去加一个 finishIconClassName 和 errowIconClassName 还是比较方便扩展，之前的实现和 antd Icon 绑定太死了。来个 PR 吧~

**Comment by warmhug** [comment]
算了，感觉越加越混乱，这个组件里的主要逻辑，在 antd-mobile 里几乎要重写一份，有空可以 review 下：https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/index.web.tsx
