### ISSUE TITLE
两个tab 里面都有 steps 组件的样式错位问题

### ISSUE THREAD

**Issue by greenplumm** [react-component/steps#26]
两个tab 里面都有 steps 组件 ，然后切换两个tab ，程序会把两个tab的steps的margin-right都修改 导致样式错位 会重新计算另一个tab里面的steps组件的margin-right值
注释Steps.jsx这里的代码 即可解决：
componentDidUpdate() {
   // this.calcLastStepOffsetWidth();
  }

**Comment by afc163** [comment]
这个代码是有用的，给个重现我看看怎么修复吧。

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by paranoidjk** [comment]
close for no response.
