### ISSUE TITLE
Change icon background color 

### ISSUE THREAD

**Issue by abdennour** [react-component/steps#29]
The default icon back color  is blue `#2db7f5` .
And the current props are : 

```js
Step.propTypes = {
  className: _react.PropTypes.string,
  prefixCls: _react.PropTypes.string,
  style: _react.PropTypes.object,
  wrapperStyle: _react.PropTypes.object,
  tailWidth: _react.PropTypes.oneOfType([_react.PropTypes.number, _react.PropTypes.string]),
  status: _react.PropTypes.string,
  iconPrefix: _react.PropTypes.string,
  icon: _react.PropTypes.node,
  adjustMarginRight: _react.PropTypes.oneOfType([_react.PropTypes.number, _react.PropTypes.string]),
  stepLast: _react.PropTypes.bool,
  stepNumber: _react.PropTypes.string,
  description: _react.PropTypes.any,
  title: _react.PropTypes.any
};
```

No props seems related to icon color .  Is it required enhancement  or already exist ? Where is if it iswas existed .

**Comment by afc163** [comment]
You can change it by writing you owner style: https://github.com/react-component/steps/blob/78b79c70c0a07b8015b8dd8206f5159cd11004d1/assets/index.less#L18

**Comment by abdennour** [comment]
Let's say: it is a great component.. 
If i found time , i will create pull-request for that .

**Comment by paranoidjk** [comment]
IMO, i do not agree with add props.  If we add `props.iconColor`,  then here will be more style props.

**Comment by benjycui** [comment]
Just use [`Steps.Step[icon]`](https://github.com/react-component/steps/blob/1a8888f38921148ed748cacfdb92ae30c93d150d/src/Step.jsx#L93) to customized node, we don't need a API for icon color.
