### ISSUE TITLE
styling does not exist

### ISSUE THREAD

**Issue by stanleycyang** [react-component/steps#31]
There is no styling included currently. In the README, was it suppose to mention adding the `.less` files?

**Comment by muhilham** [comment]
I  got it running by inserting this code in my component :

`
import 'rc-steps/assets/index.css'
import 'rc-steps/assets/iconfont.css'
`

**Comment by paranoidjk** [comment]
see demo: https://github.com/react-component/steps/blob/master/examples/simple.js#L1
