### ISSUE TITLE
How do I integrate this component with React router 

### ISSUE THREAD

**Issue by konekoya** [react-component/steps#32]
Hi @afc163 

I'm new with React and am working on a project which uses your Steps component.
I have created a couple of components that act like pages of the Steps component and is using next and prev buttons to navigate between different pages(it's actually more like a Tab component). It all works great except the URL part. I've searched from GitHub and stackoverflow for hours but still, cannot figure out how to get it working with React Router.

Thank you!

**Comment by benjycui** [comment]
Did you read this？ https://github.com/ReactTraining/react-router/blob/master/docs/API.md#pushpathorloc

**Comment by konekoya** [comment]
@benjycui Thank you! I've read through the APIs as well as tried some of the tutorials from react router tutorial([this one in particular](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/07-more-nesting)). And finally get it working! You just made my day :) 👍 🥇 💯
