### ISSUE TITLE
findDOMNode was called on an unmounted component.

### ISSUE THREAD

**Issue by jaredleechn** [react-component/steps#34]
maybe relative: https://github.com/react-component/align/issues/7

在前端监控里面发现始终在报这个错误，搜了下代码发现是下面这段的报错

https://github.com/react-component/steps/blob/2a4395038354231f8f23a7eeea8a083c5ef9786b/src/Steps.jsx#L26

**Comment by afc163** [comment]
antd 版本是？

**Comment by jaredleechn** [comment]
依赖是 2.x，最新版即可重现

重现方式是：快速切换路由使包含 rc-steps 的 component 不断被 mount 和 unmount

**Comment by yesmeck** [comment]
因为 debounce 没取消。

**Comment by yesmeck** [comment]
https://github.com/react-component/table/commit/efc5bb6b61a6ed67d574cd78c62b9aa76559b08c

**Comment by afc163** [comment]
same issue https://github.com/ant-design/ant-design/issues/5501
