### ISSUE TITLE
Click event on step number

### ISSUE THREAD

**Issue by Nishchit14** [react-component/steps#37]
Sometimes we need to go next/prev by clicking directly on step number from the process bar, It is good if we put onClick callback on click event of steps.

Btw thank you for this effort, It looks so good.

**Comment by benjycui** [comment]
@afc163 maybe we can support customizable node ![image](https://cloud.githubusercontent.com/assets/3580607/25892547/4703d560-35a7-11e7-8b43-548e90e6f4c6.png), so that we can solve this issue https://github.com/react-component/steps/issues/29 at the same time.

**Comment by afc163** [comment]
https://ant.design/components/steps/#components-steps-demo-icon

It is supported via `icon`.

**Comment by benjycui** [comment]
Yep, it seems that it works fine now.. I remember that it will broke style when we mix `icon` and default number..

http://codepen.io/benjycui/pen/vmRELd?editors=0011

@Nishchit14 so, just use [`Steps.Step[icon]`](https://github.com/react-component/steps/blob/1a8888f38921148ed748cacfdb92ae30c93d150d/src/Step.jsx#L93)
