### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by ghostsquad** [react-component/steps#40]
It seems the assets are missing from the package.

![image](https://user-images.githubusercontent.com/903488/30502947-300ef364-9a1d-11e7-91db-9a52109cbb30.png)

![image](https://user-images.githubusercontent.com/903488/30502971-4729b5d4-9a1d-11e7-85d0-6cea4f2ce261.png)

```
"rc-steps": "^3.0.0",
```

**Comment by afc163** [comment]
https://unpkg.com/rc-steps@3.0.0/assets/

**Comment by ghostsquad** [comment]
?? This is installed via yarn. Why would the assets not be here?

**Comment by paranoidjk** [comment]
I tried with `yarn add rc-steps`, it works fine.

Maybe related info https://github.com/yarnpkg/yarn/issues/4093

**Comment by benjycui** [comment]
Close for no response.
