### ISSUE TITLE
本地启动的时候报错    primordials is not defined

### ISSUE THREAD

**Issue by Dolov** [react-component/steps#72]

**Comment by zombieJ** [comment]
Steps 里没有用到 `primordials`，请检查一下你的项目代码或者其依赖。

**Comment by Dolov** [comment]
> Steps 里没有用到 `primordials`，请检查一下你的项目代码或者其依赖。

在本地 clone 了项目之后 yarn     然后 yarn start    就报错这个错了

<img width="848" alt="WX20190531-225356@2x" src="https://user-images.githubusercontent.com/19704420/58714337-1a205c80-83f7-11e9-9b92-358bbd2e2621.png">

**Comment by zombieJ** [comment]
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
