### ISSUE TITLE
Steps not clickable

### ISSUE THREAD

**Issue by Morriz** [react-component/steps#8]
Can't click the steps, so it's impossible to go back...

**Comment by benjycui** [comment]
You can add buttons to go back. See: http://react-component.github.io/steps/examples/nextStep.html

**Comment by Morriz** [comment]
But that is not the same. A user should be able to jump to a section imo

**Comment by benjycui** [comment]
Add `onClick: Function(index)` to `Steps`? @yiminghe

**Comment by yiminghe** [comment]
@afc163

**Comment by afc163** [comment]
https://github.com/react-component/steps/commit/e16fb802963aa25a260d6f055c1a5ff7eb91b37f#diff-65ff96fe63d3ad6c198015c5f884a782R44

`onClick` already supported in `<Step />`.
